package com.becomejavasenior;

/**
 * @author Anton Sakhno <sakhno83@gmail.com>
 */
public enum ContactFilters {
    WITHOUT_TASKS, WITH_OVERDUE_TASKS, WITHOUT_DEALS, WITHOUT_OPEN_DEALS, PRIMARY_CONTACTS, CONVERSATION_CONTACTS,
    MAKING_DECISION_CONTACTS, APPROVAL_CONTRACT_CONTACTS, SUCCESS_CONTACTS, NOT_REALISED_CONTACTS
}
